api_version: loop.exchange/v1alpha1
kind: EngineConfig
repositories:
  - id: official
    url: oci://ghcr.io/loop-exchange-protocol
    credential: GHCR_TOKEN
    auto_install: true
    trusted_namespaces:
      - loop.exchange
bindings:
  - kind: provider
    contract:
      namespace: loop.exchange
      name: git
      version: v1
    implementation:
      source: repository
      package:
        namespace: loop.exchange
        name: provider-git
        version: 0.1.0-alpha.4
      digest: sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
